name: Build on Ubuntu

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [ Debug ]
        pgsql_version: [ 13, 14, 15, 16, 17, 18 ]

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
          submodules: true

      - name: Prepare container(apt download)
        shell: bash
        run: |
          sudo apt update
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
          sudo apt update
          sudo apt-get install -yqf build-essential libboost-all-dev libgtest-dev postgresql-${{ matrix.pgsql_version }} postgresql-server-dev-${{ matrix.pgsql_version }}
          echo
          pg_config

      - name: Prepare container(onnxruntime)
        shell: bash
        run: |
          ./onnxruntime-server/.github/actions/download-onnxruntime-linux.sh

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_C_COMPILER=gcc
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DPG_CONFIG=/usr/lib/postgresql/${{ matrix.pgsql_version }}/bin/pg_config
          -S ${{ github.workspace }}

      - name: Build
        run: |
          cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} --parallel 4
          sudo cmake --install ${{ steps.strings.outputs.build-output-dir }}/pg_onnx

      - name: (Cache) Restore test fixtures
        uses: actions/cache/restore@v4
        with:
          path: onnxruntime-server/test/fixture
          key: test-fixtures-v1
          fail-on-cache-miss: true

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --extra-verbose --build-config ${{ matrix.build_type }}

      - name: Upload artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: output-artifact-ubuntu-pgsql${{ matrix.pgsql_version }}
          path: ${{ steps.strings.outputs.build-output-dir }}/pg_onnx/regression.*
          if-no-files-found: ignore
          overwrite: true

      - name: Create Success Badge
        if: success()
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: a6e5351fdbced3d780f4f153e99de723
          filename: pg_onnx-ubuntu-pgsql${{ matrix.pgsql_version }}.json
          label: PostgreSQL ${{ matrix.pgsql_version }}
          message: passing
          color: green

      - name: Create Failure Badge
        if: failure()
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: a6e5351fdbced3d780f4f153e99de723
          filename: pg_onnx-ubuntu-pgsql${{ matrix.pgsql_version }}.json
          label: PostgreSQL ${{ matrix.pgsql_version }}
          message: failing
          color: red