name: Build on MacOS

permissions:
  contents: read

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [ Debug ]
        pgsql_version: [ 14, 15, 16, 17, 18 ]

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
          submodules: true

      - name: Prepare container(homebrew)
        shell: bash
        run: |
          brew update
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake boost googletest protobuf onnx abseil re2 postgresql@${{ matrix.pgsql_version }}
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} ./onnxruntime-server/.github/actions/download-onnxruntime-osx.sh

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=clang++
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DPG_CONFIG=/opt/homebrew/opt/postgresql@${{ matrix.pgsql_version }}/bin/pg_config
          -S ${{ github.workspace }}

      - name: Build
        run: |
          cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} --parallel 4
          sudo cmake --install ${{ steps.strings.outputs.build-output-dir }}/pg_onnx

      - name: (Cache) Restore test fixtures
        uses: actions/cache/restore@v4
        with:
          path: onnxruntime-server/test/fixture
          key: test-fixtures-v1
          fail-on-cache-miss: true

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --extra-verbose --build-config ${{ matrix.build_type }}

      - name: Upload artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: output-artifact-macos-pgsql${{ matrix.pgsql_version }}
          path: ${{ steps.strings.outputs.build-output-dir }}/pg_onnx/regression.*
          if-no-files-found: ignore
          overwrite: true

      - name: Create Success Badge
        if: success()
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: a6e5351fdbced3d780f4f153e99de723
          filename: pg_onnx-macos-pgsql${{ matrix.pgsql_version }}.json
          label: PostgreSQL ${{ matrix.pgsql_version }}
          message: passing
          color: green

      - name: Create Failure Badge
        if: failure()
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: a6e5351fdbced3d780f4f153e99de723
          filename: pg_onnx-macos-pgsql${{ matrix.pgsql_version }}.json
          label: PostgreSQL ${{ matrix.pgsql_version }}
          message: failing
          color: red